Add carousel with autoplay and animated indicator
hongshancapital/interview-assignments pull request #571
Opened 2021-12-05 20:27 UTC by Sup-Friday

### Notes
- Added carousel with autoplay and animated indicator

### Contact Me
- Name: Shuo Feng
- Email: shuo.s.feng@gmail.com

2021-12-06 02:33 UTC, YuBoxiang commented on frontend/src/components/Carousel/Carousel.tsx
> +interface CarouselProps {}
声明一个空 interface 的意义是？

2021-12-06 02:34 UTC, YuBoxiang commented on frontend/src/components/Carousel/CarouselItem/CarouselItem.tsx
> +                height: height ? height : "100%",
可否稍作重构，完全使用 css 控制？

2021-12-06 02:38 UTC, YuBoxiang requested changes
感谢PR ！ 设计稿还原得很棒，除了下方的 indicator 给顶到了 view 外面，可否稍作修改，一屏显示完，无需y scroll？
![image](https://user-images.githubusercontent.com/72589370/144778239-3f6d93cd-a413-4faf-be7b-f01f625e3935.png)

2021-12-07 00:47 UTC, Sup-Friday commented on frontend/src/components/Carousel/Carousel.tsx
> +interface CarouselProps {}
这个是为了保证函数组件的实践遵循一定的规范（所有的组件一定会有一个对应的interface）

2021-12-07 00:48 UTC, Sup-Friday commented on frontend/src/components/Carousel/CarouselItem/CarouselItem.tsx
> +                height: height ? height : "100%",
考虑到width和height这两个接口没有被使用，所以我计划去掉他们，然后用一个css class来设定这个组件的长宽。请问这样可以吗？

2021-12-07 01:03 UTC, Sup-Friday commented
感谢快速的review！会发布一个新的commit来更新一部分逻辑

2021-12-08 06:00 UTC, Sup-Friday commented
新的改动已经提交，麻烦Review了！

2021-12-08 08:21 UTC, YuBoxiang commented on frontend/src/components/Carousel/CarouselItem/CarouselItem.tsx
> +                height: height ? height : "100%",
没问题

2021-12-08 08:27 UTC, YuBoxiang commented
![image](https://user-images.githubusercontent.com/72589370/145174429-77ae97b2-6ca0-4356-9078-8050f9f61d74.png)

感觉宽高没有自适应？可否再适配一下？

2021-12-09 01:56 UTC, Sup-Friday commented
感谢回复！我也有几个问题：

1. 在`要求`、`加分项`、以及Demo中没有提及Responsive design，如果这两项是需求项，是否应该在出题的时候明确说明？
<img width="449" alt="Screen Shot 2021-12-08 at 5 50 11 PM" src="https://user-images.githubusercontent.com/44722646/145319718-46793f18-cbc6-4791-9441-a99932795d0c.png">
1. Responsive design的规范是什么？换言之，假定背景图片的大小是W1 * H1，窗口大小是W2 * H2，那么这个carousel的组件的大小是什么？

2021-12-09 02:49 UTC, YuBoxiang commented
> 感谢回复！当前的Responsive design是根据图片大小等比例缩放，如果你把window缩小到小于1024px会看到。另外，我也有几个问题：
> 
> 1. 在`要求`、`加分项`、以及Demo中没有提及Responsive design，如果这两项是需求项，是否应该在出题的时候明确说明？<img alt="Screen Shot 2021-12-08 at 5 50 11 PM" width="449" src="https://user-images.githubusercontent.com/44722646/145319718-46793f18-cbc6-4791-9441-a99932795d0c.png">

这个没有 responsive design 那么高要求，就是让内容占满浏览器 viewport，例如 Apple 网站的产品页面，一般不会留有白边吧？

> 2. Responsive design的规范是什么？换言之，假定背景图片的大小是W1 * H1，窗口大小是W2 * H2，那么这个carousel的组件的大小是什么？

没有背景图片，只有背景色

2024-04-11 11:47 UTC, closed without merging